### ISSUE TITLE
Plugin names suitable to helix

### ISSUE THREAD

**Issue by zim0369** [zim0369/helix_plugins#1]
If there's a preexisting plugin with a name suited to that editor such as "vim-move" then these names should be edited to something new like "helix-move", "helix-transport", etc.

Basically, anything with a name with helix in it or a new suitable name.

**Comment by metafates** [comment]
I think it would be better to have it a suffix instead which is pretty common for (n)vim plugins.
Something like `dnatree.hx` but looks like `.hx` is [already taken](https://fileinfo.com/extension/hx) so maybe using `.helix` is an option --> `dnatree.helix`

**Comment by zim0369** [comment]
> I think it would be better to have a suffix instead which is pretty common for (n)vim plugins. Something like `dnatree.hx` but looks like `.hx` is [already taken](https://fileinfo.com/extension/hx) so maybe using `.helix` is an option --> `dnatree.helix`

That's good too.

**Comment by zim0369** [comment]
Naming will be the privilege of anyone who chooses to create the plugin. This repo is just an accumulation of what plugins helix users desire.
